### ISSUE TITLE
make报错

### ISSUE THREAD

**Issue by liangxm-0323** [amd/amd_smi_exporter#1]
```bash
# github.com/amd/go_amd_smi
/bin/ld: cannot find -lrocm_smi64
/bin/ld: cannot find -lgoamdsmi_shim64
collect2: error: ld returned 1 exit status
make: *** [build] Error 2
```
查看go_amd_smi相关依赖gitHub地址404，请问有其他的解决方法吗

**Comment by nchatrad** [comment]
You need the rocm and smi libraries installed. Please refer to https://github.com/amd/esmi_ib_library/docs/README.md, https://github.com/amd/go_amd_smi/README.md, and https://github.com/RadeonOpenCompute/rocm_smi_lib/README.md for the build and installation instructions.
